//! Property-based round-trip tests for every type that crosses the
//! simulator boundary.
//!
//! Each test asserts `bincode::deserialize(bincode::serialize(x)) == x`
//! over arbitrary instances generated by `proptest`. Together with the
//! pinned-byte goldens in `golden.rs`, these tests catch *both* of:
//!
//! * **Pinned vector drift** — `golden.rs` traps any change to the
//!   bytes for a *single* known input.
//! * **Field-reorder drift** — these proptests trap changes that
//!   shift the wire format for *unseen* field combinations, including
//!   combinations the golden vector does not exercise (empty Vecs,
//!   max-precision Stats, every HeroClass × Rarity pair, etc.).

use proptest::collection::vec;
use proptest::prelude::*;
use wr_core::{
    BattleEvent, BattleInput, BattleOutput, BattleTarget, Hero, HeroClass, Rarity, Roster, Side,
    Stat, StatusEffect, TerrainModifier, XpGrant,
};

// ---------------------------------------------------------------------
//   Strategies — bounded so we don't generate i64::MIN-class pathologies
//   that the game does not produce in practice.
// ---------------------------------------------------------------------

fn arb_stat() -> impl Strategy<Value = Stat> {
    // Bounded to ~[-1e6, 1e6] in fixed-point bits. Plenty of range for
    // any combat quantity while staying well clear of overflow in
    // downstream arithmetic.
    (-1_000_000i64..=1_000_000i64).prop_map(|v| Stat::from_bits(v << 8))
}

fn arb_class() -> impl Strategy<Value = HeroClass> {
    prop_oneof![
        Just(HeroClass::Infantry),
        Just(HeroClass::Armor),
        Just(HeroClass::Artillery),
        Just(HeroClass::Support),
        Just(HeroClass::Command),
    ]
}

fn arb_rarity() -> impl Strategy<Value = Rarity> {
    prop_oneof![
        Just(Rarity::Common),
        Just(Rarity::Uncommon),
        Just(Rarity::Rare),
        Just(Rarity::Epic),
        Just(Rarity::Legendary),
        Just(Rarity::Mythic),
    ]
}

fn arb_status_effect() -> impl Strategy<Value = StatusEffect> {
    prop_oneof![
        Just(StatusEffect::Burning),
        Just(StatusEffect::Poisoned),
        Just(StatusEffect::Frozen),
        Just(StatusEffect::Stunned),
        Just(StatusEffect::Shielded),
        Just(StatusEffect::Enraged),
        Just(StatusEffect::Thorns),
        Just(StatusEffect::Regenerating),
    ]
}

fn arb_side() -> impl Strategy<Value = Side> {
    prop_oneof![Just(Side::A), Just(Side::B)]
}

fn arb_hero() -> impl Strategy<Value = Hero> {
    // proptest tuple Strategy maxes out at 12 elements; nest the
    // six combat stats into one sub-tuple to stay under the limit.
    let stats = (arb_stat(), arb_stat(), arb_stat(), arb_stat(), arb_stat(), arb_stat());
    (
        any::<u64>(),
        arb_class(),
        arb_rarity(),
        stats,
        vec(any::<u32>(), 0..4),
        any::<u32>(),
        any::<u64>(),
        vec(any::<u32>(), 0..4),
    )
        .prop_map(
            |(
                id,
                class,
                rarity,
                (hp, atk, def, speed, crit_rate, crit_damage),
                abilities,
                veterancy,
                xp,
                equipped_items,
            )| Hero {
                id,
                class,
                rarity,
                hp,
                atk,
                def,
                speed,
                crit_rate,
                crit_damage,
                abilities,
                veterancy,
                xp,
                equipped_items,
            },
        )
}

fn arb_roster() -> impl Strategy<Value = Roster> {
    (
        any::<[u8; 20]>(),
        vec(arb_hero(), 1..=4),
        any::<[u8; 32]>(),
    )
        .prop_map(|(owner, heroes, commitment_hash)| Roster {
            owner,
            heroes,
            commitment_hash,
        })
}

fn arb_terrain() -> impl Strategy<Value = TerrainModifier> {
    (arb_stat(), arb_stat(), arb_stat()).prop_map(|(atk_mod, def_mod, speed_mod)| {
        TerrainModifier { atk_mod, def_mod, speed_mod }
    })
}

fn arb_battle_input() -> impl Strategy<Value = BattleInput> {
    (
        any::<u64>(),
        arb_roster(),
        arb_roster(),
        any::<[u8; 32]>(),
        any::<u32>(),
        proptest::option::of(arb_terrain()),
    )
        .prop_map(|(round, roster_a, roster_b, seed, ruleset_version, terrain)| BattleInput {
            round,
            roster_a,
            roster_b,
            seed,
            ruleset_version,
            terrain,
        })
}

fn arb_xp_grant() -> impl Strategy<Value = XpGrant> {
    (any::<u64>(), any::<u64>(), any::<u32>()).prop_map(|(hero, amount, veterancy_delta)| {
        XpGrant { hero, amount, veterancy_delta }
    })
}

fn arb_battle_event() -> impl Strategy<Value = BattleEvent> {
    prop_oneof![
        (any::<u8>(), any::<u8>()).prop_map(|(roster_a_size, roster_b_size)| {
            BattleEvent::BattleStart { roster_a_size, roster_b_size }
        }),
        any::<u32>().prop_map(|tick| BattleEvent::TurnStart { tick }),
        (any::<u32>(), any::<u64>(), any::<u64>(), arb_stat(), any::<bool>()).prop_map(
            |(tick, src, dst, damage, is_crit)| BattleEvent::Attack {
                tick, src, dst, damage, is_crit,
            },
        ),
        (any::<u32>(), any::<u64>(), any::<u64>(), arb_stat()).prop_map(
            |(tick, src, dst, amount)| BattleEvent::Heal { tick, src, dst, amount },
        ),
        (any::<u32>(), any::<u64>(), any::<u32>(), vec(any::<u64>(), 0..4)).prop_map(
            |(tick, src, ability, targets)| BattleEvent::Ability {
                tick, src, ability, targets,
            },
        ),
        (any::<u32>(), any::<u64>(), arb_status_effect(), any::<u8>()).prop_map(
            |(tick, hero, status, duration)| BattleEvent::StatusApplied {
                tick, hero, status, duration,
            },
        ),
        (any::<u32>(), any::<u64>(), arb_status_effect()).prop_map(|(tick, hero, status)| {
            BattleEvent::StatusExpired { tick, hero, status }
        }),
        (any::<u32>(), any::<u64>(), proptest::option::of(any::<u64>())).prop_map(
            |(tick, hero, killer)| BattleEvent::Death { tick, hero, killer },
        ),
        (any::<u32>(), arb_side()).prop_map(|(tick, winner)| BattleEvent::BattleEnd {
            tick, winner,
        }),
    ]
}

fn arb_battle_output() -> impl Strategy<Value = BattleOutput> {
    (
        any::<u64>(),
        arb_side(),
        vec(any::<u64>(), 0..4),
        vec(any::<u64>(), 0..4),
        vec(arb_battle_event(), 0..6),
        vec(arb_xp_grant(), 0..4),
        any::<u32>(),
        any::<[u8; 32]>(),
    )
        .prop_map(
            |(round, winner, survivors_a, survivors_b, events, xp_grants, total_ticks, output_hash)| {
                BattleOutput {
                    round,
                    winner,
                    survivors_a,
                    survivors_b,
                    events,
                    xp_grants,
                    total_ticks,
                    output_hash,
                }
            },
        )
}

// ---------------------------------------------------------------------
//   Property tests
// ---------------------------------------------------------------------

fn assert_roundtrip<T>(value: &T)
where
    T: serde::Serialize + serde::de::DeserializeOwned + std::fmt::Debug + PartialEq,
{
    let bytes = bincode::serialize(value).expect("serialize");
    let back: T = bincode::deserialize(&bytes).expect("deserialize");
    assert_eq!(&back, value);
}

proptest! {
    #![proptest_config(ProptestConfig {
        cases: 256,
        ..ProptestConfig::default()
    })]

    #[test]
    fn hero_roundtrips(h in arb_hero()) {
        let bytes = bincode::serialize(&h)?;
        let back: Hero = bincode::deserialize(&bytes)?;
        // Hero doesn't derive PartialEq; compare field-by-field.
        prop_assert_eq!(back.id,             h.id);
        prop_assert_eq!(back.class,          h.class);
        prop_assert_eq!(back.rarity,         h.rarity);
        prop_assert_eq!(back.hp,             h.hp);
        prop_assert_eq!(back.atk,            h.atk);
        prop_assert_eq!(back.def,            h.def);
        prop_assert_eq!(back.speed,          h.speed);
        prop_assert_eq!(back.crit_rate,      h.crit_rate);
        prop_assert_eq!(back.crit_damage,    h.crit_damage);
        prop_assert_eq!(back.abilities,      h.abilities);
        prop_assert_eq!(back.veterancy,      h.veterancy);
        prop_assert_eq!(back.xp,             h.xp);
        prop_assert_eq!(back.equipped_items, h.equipped_items);
    }

    #[test]
    fn roster_roundtrips(r in arb_roster()) {
        let bytes = bincode::serialize(&r)?;
        let back: Roster = bincode::deserialize(&bytes)?;
        prop_assert_eq!(back.owner,           r.owner);
        prop_assert_eq!(back.heroes.len(),    r.heroes.len());
        prop_assert_eq!(back.commitment_hash, r.commitment_hash);
    }

    #[test]
    fn battle_input_roundtrips(input in arb_battle_input()) {
        let bytes = bincode::serialize(&input)?;
        let back: BattleInput = bincode::deserialize(&bytes)?;
        prop_assert_eq!(back.round,           input.round);
        prop_assert_eq!(back.seed,            input.seed);
        prop_assert_eq!(back.ruleset_version, input.ruleset_version);
    }

    #[test]
    fn battle_event_roundtrips(ev in arb_battle_event()) {
        let bytes = bincode::serialize(&ev)?;
        let back: BattleEvent = bincode::deserialize(&bytes)?;
        // Re-encode and compare bytes — BattleEvent has Vec fields and
        // doesn't derive PartialEq.
        let bytes2 = bincode::serialize(&back)?;
        prop_assert_eq!(bytes, bytes2);
    }

    #[test]
    fn battle_output_roundtrips(out in arb_battle_output()) {
        let bytes = bincode::serialize(&out)?;
        let back: BattleOutput = bincode::deserialize(&bytes)?;
        let bytes2 = bincode::serialize(&back)?;
        prop_assert_eq!(bytes, bytes2);
    }

    #[test]
    fn xp_grant_roundtrips(g in arb_xp_grant()) {
        assert_roundtrip(&g);
    }

    #[test]
    fn battle_target_roundtrips(t in prop_oneof![
        any::<[u8; 20]>().prop_map(BattleTarget::Roster),
        any::<u32>().prop_map(BattleTarget::Territory),
    ]) {
        assert_roundtrip(&t);
    }
}
